"""remove wallet_id and add currency_code

Revision ID: 1d075ec8b64f
Revises: 74a87f9f6707
Create Date: 2025-03-26 21:37:44.348304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d075ec8b64f'
down_revision = '74a87f9f6707'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction_crypto', schema=None) as batch_op:
        batch_op.drop_column('wallet_id')
        batch_op.drop_column('receiving_wallet_id')

    with op.batch_alter_table('transaction_fiat', schema=None) as batch_op:
        batch_op.add_column(sa.Column('currency_code', sa.String(length=3), nullable=False))

    with op.batch_alter_table('transaction_fiat_to_crypto', schema=None) as batch_op:
        batch_op.drop_column('wallet_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction_fiat_to_crypto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('wallet_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False))

    with op.batch_alter_table('transaction_fiat', schema=None) as batch_op:
        batch_op.drop_column('currency_code')

    with op.batch_alter_table('transaction_crypto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('receiving_wallet_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('wallet_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
