"""Initial migration.

Revision ID: 74a87f9f6707
Revises: 
Create Date: 2025-03-22 22:00:09.376594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74a87f9f6707'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transaction_crypto',
    sa.Column('transaction_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=False),
    sa.Column('wallet_id', sa.String(length=100), nullable=False),
    sa.Column('receiving_wallet_id', sa.String(length=100), nullable=False),
    sa.Column('receiving_user_id', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('from_token_id', sa.Integer(), nullable=False),
    sa.Column('from_amount', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('to_token_id', sa.Integer(), nullable=False),
    sa.Column('to_amount', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('limit_price', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('usdt_fee', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('creation', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('completion', sa.DateTime(timezone=True), nullable=True),
    sa.Column('order_type', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('transaction_id')
    )
    op.create_table('transaction_fiat',
    sa.Column('transaction_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=15), nullable=False),
    sa.Column('creation', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('confirmation', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('transaction_id')
    )
    op.create_table('transaction_fiat_to_crypto',
    sa.Column('transaction_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=False),
    sa.Column('wallet_id', sa.String(length=100), nullable=False),
    sa.Column('from_amount', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('to_amount', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('direction', sa.String(length=15), nullable=False),
    sa.Column('limit_price', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('status', sa.String(length=15), nullable=False),
    sa.Column('creation', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('confirmation', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('transaction_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaction_fiat_to_crypto')
    op.drop_table('transaction_fiat')
    op.drop_table('transaction_crypto')
    # ### end Alembic commands ###
