"""rmv receivinguserid add partial fulfilment.

Revision ID: 7ca1ea8fbc70
Revises: 1d075ec8b64f
Create Date: 2025-03-30 17:17:40.820412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ca1ea8fbc70'
down_revision = '1d075ec8b64f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction_crypto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('from_amount_actual', sa.Numeric(precision=18, scale=8), nullable=True))
        batch_op.add_column(sa.Column('to_amount_actual', sa.Numeric(precision=18, scale=8), nullable=True))
        batch_op.drop_column('receiving_user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction_crypto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('receiving_user_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.drop_column('to_amount_actual')
        batch_op.drop_column('from_amount_actual')

    # ### end Alembic commands ###
