"""remove usdt_fee

Revision ID: a41ecd744d08
Revises: c13d9eefff62
Create Date: 2025-04-07 23:02:31.705512

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a41ecd744d08'
down_revision = 'c13d9eefff62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction_crypto', schema=None) as batch_op:
        batch_op.drop_column('usdt_fee')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction_crypto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('usdt_fee', sa.NUMERIC(precision=18, scale=8), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
