"""change token_id data type

Revision ID: c5757f533cd9
Revises: 7ca1ea8fbc70
Create Date: 2025-03-30 17:46:27.884511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5757f533cd9'
down_revision = '7ca1ea8fbc70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction_crypto', schema=None) as batch_op:
        batch_op.alter_column('from_token_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=15),
               existing_nullable=False)
        batch_op.alter_column('to_token_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=15),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction_crypto', schema=None) as batch_op:
        batch_op.alter_column('to_token_id',
               existing_type=sa.String(length=15),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('from_token_id',
               existing_type=sa.String(length=15),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
