"""reinitalise tables

Revision ID: 13749c5d948a
Revises: 
Create Date: 2025-03-31 11:43:44.380589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13749c5d948a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crypto_holding',
    sa.Column('user_id', sa.String(length=100), nullable=False),
    sa.Column('token_id', sa.String(length=15), nullable=False),
    sa.Column('actual_balance', sa.Float(), nullable=False),
    sa.Column('held_balance', sa.Float(), nullable=False),
    sa.Column('updated_on', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('user_id', 'token_id')
    )
    op.create_table('crypto_token',
    sa.Column('token_id', sa.String(length=15), nullable=False),
    sa.Column('token_name', sa.String(length=100), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('token_id'),
    sa.UniqueConstraint('token_id'),
    sa.UniqueConstraint('token_name')
    )
    op.create_table('crypto_wallet',
    sa.Column('user_id', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('crypto_wallet')
    op.drop_table('crypto_token')
    op.drop_table('crypto_holding')
    # ### end Alembic commands ###
