"""Initial migration.

Revision ID: 4061b117b055
Revises: 
Create Date: 2025-03-25 02:47:42.004218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4061b117b055'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crypto_token',
    sa.Column('token_id', sa.String(length=10), nullable=False),
    sa.Column('token_name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('token_id'),
    sa.UniqueConstraint('token_id'),
    sa.UniqueConstraint('token_name')
    )
    op.create_table('crypto_wallet',
    sa.Column('wallet_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('wallet_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('crypto_holding',
    sa.Column('holding_id', sa.UUID(), nullable=False),
    sa.Column('wallet_id', sa.UUID(), nullable=False),
    sa.Column('token_id', sa.String(length=10), nullable=False),
    sa.Column('actual_balance', sa.Float(), nullable=False),
    sa.Column('held_balance', sa.Float(), nullable=False),
    sa.Column('updated_on', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['token_id'], ['crypto_token.token_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['wallet_id'], ['crypto_wallet.wallet_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('holding_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('crypto_holding')
    op.drop_table('crypto_wallet')
    op.drop_table('crypto_token')
    # ### end Alembic commands ###
