"""remove salt from user

Revision ID: 7dbef72436f9
Revises: 513640c5d448
Create Date: 2025-03-07 13:29:15.230325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7dbef72436f9'
down_revision = '513640c5d448'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_authenticate', schema=None) as batch_op:
        batch_op.drop_column('salt')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_authenticate', schema=None) as batch_op:
        batch_op.add_column(sa.Column('salt', sa.VARCHAR(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
