"""initial migration.

Revision ID: a4b98976068d
Revises: 
Create Date: 2025-05-03 15:46:53.713749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4b98976068d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('transaction_id', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=False),
    sa.Column('order_type', sa.String(length=20), nullable=True),
    sa.Column('from_token_id', sa.String(length=50), nullable=False),
    sa.Column('to_token_id', sa.String(length=50), nullable=False),
    sa.Column('from_amount', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('limit_price', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('creation', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('transaction_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orders')
    # ### end Alembic commands ###
