"""Initial migration.

Revision ID: 8a9c144bdecc
Revises: 
Create Date: 2025-03-24 22:36:46.492198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a9c144bdecc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fiat_currency',
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('rate', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('currency_code')
    )
    op.create_table('fiat_account',
    sa.Column('user_id', sa.String(length=100), nullable=False),
    sa.Column('balance', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['currency_code'], ['fiat_currency.currency_code'], ),
    sa.PrimaryKeyConstraint('user_id', 'currency_code')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fiat_account')
    op.drop_table('fiat_currency')
    # ### end Alembic commands ###
