name: 'Release Workflow'

on:
  push:
    branches:
      - main  # Triggers the workflow on pushes to the main branch

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Increment Version
        id: increment_version
        uses: reecetech/version-increment@2024.10.1
        with:
          scheme: semver
          increment: patch  # Options: major, minor, patch

      - name: Create Tag
        id: create_tag
        run: |
          git tag ${{ steps.increment_version.outputs.version }}
          git push origin ${{ steps.increment_version.outputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Changelog
        id: build_changelog
        uses: mikepenz/release-changelog-builder-action@v5  # ✅ Revert to v5
        with:
          configuration: .github/release-changelog-builder-config.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Debug Changelog Output
        run: |
          echo "Changelog Output:"
          echo "${{ steps.build_changelog.outputs.changelog }}"
          echo "${{ steps.build_changelog.outputs.changelog }}" > CHANGELOG.txt

      - name: Verify Changelog File Exists
        run: |
          if [ ! -s CHANGELOG.txt ]; then
            echo "❌ No changelog generated. Failing the build."
            exit 1
          else
            echo "✅ Changelog successfully generated."
          fi

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.increment_version.outputs.version }}
          release_name: "Release ${{ steps.increment_version.outputs.version }}"
          body_path: CHANGELOG.txt  # ✅ Uses generated changelog file
